### ISSUE TITLE
Last resort key still in documentation

### ISSUE THREAD

**Issue by bneijt** [signalapp/libsignal-service-java#63]
https://github.com/signalapp/libsignal-protocol-java/commit/111df84ac05ac4cd1fe98c0b9e64335eeac83122 removed the Last Resort Pre Key, but it's still mentioned in the documentation/README.md of this git repository.

**Comment by ahachmann** [comment]
Yeah, and I am wondering what the correct way of usage now is. Could anyone please help me out?

**Comment by croesch** [comment]
Did you find a solution? I got this far and am not sure what parts are wrong, but I receive the SMS - I just am not able to verify it - I receive HTTP 403, so I guess something with the code/verification code is wrong.

```
    IdentityKeyPair identityKeyPair = KeyHelper.generateIdentityKeyPair();
    int registrationId = KeyHelper.generateRegistrationId(false);
    int startId = 0;
    List<PreKeyRecord> oneTimePreKeys = KeyHelper.generatePreKeys(startId, 100);
    SignedPreKeyRecord signedPreKey = KeyHelper.generateSignedPreKey(identityKeyPair, 5);

    idStore = new IdStore(identityKeyPair, registrationId);

    MyPreKeyStore preKeyStore = new MyPreKeyStore();
    MySignedPreKeyStore signedPreKeyStore = new MySignedPreKeyStore();
    MySessionStore sessionStore = new MySessionStore();

    signedPreKeyStore.storeSignedPreKey(signedPreKey.getId(), signedPreKey);

    MyIdentityKeyStore identityKeyStore = new MyIdentityKeyStore(identityKeyPair, registrationId);

    store = new MySignalStore(identityKeyStore, preKeyStore, sessionStore, signedPreKeyStore);

    SignalServiceAccountManager accountManager = new SignalServiceAccountManager(config, USERNAME, PASSWORD,
        USER_AGENT);
    accountManager.requestSmsVerificationCode(false);
    System.out.println("Enter SMS verification code: ");
    String verificationCode = new BufferedReader(new InputStreamReader(System.in)).readLine();
    String signalingKey = "..."; // FIXME hard coded? What should be the content
    // FIXME from Android project, but does it work like that? Does it need to be saved?
    byte[] secret = new byte[32];
    new SecureRandom().nextBytes(secret);
    byte[] unidentifiedAccessKey = UnidentifiedAccess.deriveAccessKeyFrom(secret);
    accountManager.verifyAccountWithCode(verificationCode, signalingKey, registrationId, false, null,
        unidentifiedAccessKey, true /* FIXME true/false? */);
    accountManager.setPreKeys(identityKeyPair.getPublicKey(), signedPreKey, oneTimePreKeys);

    // save at the end to ensure nothing is written in case of an error
    idStore.save();
    signedPreKeyStore.save();
```

Certainly would appreciate some hint where to find proper documentation, too ;-) 

Can the `password`, `signalingKey` and `unidentifiedAccessKey` be randomly generated? What size limits exist? Should they differ from client to client? Should they be stored for use within later communication?

**Comment by magnusja** [comment]
I am getting this...

```
Exception in thread "main" java.lang.NullPointerException: No password supplied for PKCS#12 KeyStore.
	at org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.engineLoad(Unknown Source)
	at java.base/java.security.KeyStore.load(KeyStore.java:1472)
	at java.base/sun.security.ssl.TrustStoreManager$TrustAnchorManager.loadKeyStore(TrustStoreManager.java:365)
	at java.base/sun.security.ssl.TrustStoreManager$TrustAnchorManager.getTrustedCerts(TrustStoreManager.java:313)
	at java.base/sun.security.ssl.TrustStoreManager.getTrustedCerts(TrustStoreManager.java:55)
	at java.base/sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:49)
	at java.base/javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:278)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.createAttachmentClient(PushServiceSocket.java:1039)
	at org.whispersystems.signalservice.internal.push.PushServiceSocket.<init>(PushServiceSocket.java:164)
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.<init>(SignalServiceAccountManager.java:100)
	at org.whispersystems.signalservice.api.SignalServiceAccountManager.<init>(SignalServiceAccountManager.java:93)
	at me.jahnen.service.signal.signal.RegisterKt$main$1.invoke(register.kt:47)
	at me.jahnen.service.signal.signal.RegisterKt$main$1.invoke(register.kt)
	at com.xenomachina.argparser.SystemExitExceptionKt.mainBody(SystemExitException.kt:74)
	at com.xenomachina.argparser.SystemExitExceptionKt.mainBody$default(SystemExitException.kt:72)
	at me.jahnen.service.signal.signal.RegisterKt.main(register.kt:25)
```


@croesch Can you please tell me what your Store implementations look like? How does the Signal API know about them (I assume it is using all the key storages?)
